name: update
on:
  workflow_dispatch: {}
  schedule:
    - cron: '35 * * * *'
jobs:
  update:
    name: update
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.15.0'
      - run: make bin/klbjplaylist
      - run: bin/klbjplaylist
      - name: git update
        run: |
          git add data
          git config --global user.email "noreply@github.com"
          git config --global user.name "update action"
          git commit -m "updata data"
          git push
